const practice=[
['Air pressure builds normally while idling, but drops steadily during repeated brake applications. What does this most strongly suggest?',['Air demand exceeds supply from leaks or a weak compressor','The parking brake valve is holding pressure too long','Normal air use that requires no inspection','ABS is releasing pressure to prevent lockup'],0,'The system may keep up at idle but fail under brake demand when supply is weak or air is escaping.'],
['When should the low-air warning activate?',['Before pressure falls below 60 psi','Only after spring brakes apply','At normal cut-out pressure','When the engine is switched off'],0,'The warning must activate before pressure becomes dangerously low, commonly before 60 psi.'],
['What is the safest response to a low-air warning while driving?',['Stop safely as soon as possible','Pump the brakes to rebuild pressure','Increase engine speed and continue','Pull the parking brake immediately'],0,'A low-air warning signals a serious condition. Stop in a safe place before control is lost.'],
['Why drain air tanks?',['To remove moisture and oil','To increase governor cut-out pressure','To test ABS wiring','To release spring brakes'],0,'Moisture and oil can collect in air tanks and damage or freeze system components.'],
['What does the air compressor governor control?',['When the compressor pumps air','The force applied at each brake','The ABS warning lamp','The parking brake valve'],0,'The governor controls compressor cut-in and cut-out pressure.'],
['During a static leakage test, excessive pressure loss indicates what?',['A leak that requires repair','Normal brake adjustment','A fully charged system','Correct governor operation'],0,'Excessive loss means the system is leaking beyond the acceptable limit.'],
['What happens when brakes are repeatedly applied with the engine off?',['Air pressure decreases','Air pressure increases','Spring brakes release','The compressor reaches cut-out'],0,'Each application consumes stored air while the compressor is not replenishing it.'],
['Why check the slack adjusters?',['To identify excessive brake travel','To drain the supply tank','To test the governor','To inspect tire tread'],0,'Excessive movement can indicate brakes that are out of adjustment.'],
['What is brake fade?',['Reduced braking from excessive heat','A sudden rise in air pressure','Automatic ABS activation','Normal lining break-in'],0,'Heat can reduce friction and braking effectiveness, especially on long downgrades.'],
['What is the purpose of spring brakes?',['Provide parking and emergency braking','Cool the service brakes','Increase compressor output','Balance tire pressure'],0,'Powerful springs apply the brakes when air is removed or pressure becomes too low.']];
const cards=[['LOW-AIR WARNING','Why is a delayed low-air warning dangerous?','It reduces reaction time before unsafe pressure loss and spring-brake application.'],['GOVERNOR','What are cut-in and cut-out pressures?','Cut-in starts compressor loading; cut-out stops it after full pressure is reached.'],['AIR TANKS','Why must air tanks be drained?','To remove water and oil that can damage components or freeze in cold weather.'],['SPRING BRAKES','What causes spring brakes to apply?','They apply when air is released for parking or system pressure becomes dangerously low.'],['BRAKE FADE','What causes brake fade on a downgrade?','Excessive heat reduces friction and braking power. Select the proper gear before descending.'],['SLACK ADJUSTERS','What does excessive slack-adjuster movement mean?','The brakes may be out of adjustment and need inspection before driving.'],['DUAL SYSTEM','Why are there two air-pressure gauges?','They monitor the two independent parts of a dual air-brake system.'],['ABS','What does ABS help prevent?','Wheel lockup during hard braking; it does not necessarily shorten stopping distance.'],['LEAK TEST','Why perform an applied leakage test?','To find excessive leakage while the service brakes are held fully applied.'],['EMERGENCY STOP','What should you do after a low-air warning?','Stop safely as soon as possible and have the system inspected.']];
const exam=[...practice.slice(1),practice[0]];let mode='practice',index=0,score=0,answered=false,examAnswers=Array(10).fill(null),flipped=false,autoAdvance=false,autoAdvanceTimeout=null;const stage=document.querySelector('#demoStage'),title=document.querySelector('#demoTitle');
document.querySelectorAll('.demo-tabs button').forEach(b=>b.onclick=()=>{clearTimeout(autoAdvanceTimeout);document.querySelectorAll('.demo-tabs button').forEach(x=>x.classList.toggle('active',x===b));mode=b.dataset.mode;index=0;score=0;answered=false;flipped=false;examAnswers=Array(10).fill(null);title.textContent=b.childNodes[0].textContent.trim();render()});document.querySelector('#demoBack').onclick=()=>{clearTimeout(autoAdvanceTimeout);if(index>0){index--;answered=false;flipped=false;render()}};
function progress(label){return `<div class="session-progress"><span>${label}</span><b>${index+1} of 10</b><i><em style="width:${(index+1)*10}%"></em></i></div>`}function render(){mode==='flashcards'?renderCard():renderQuestion(mode==='exam')}
function renderQuestion(isExam){const q=(isExam?exam:practice)[index];stage.innerHTML=`<div class="session ${isExam?'exam-session':''}">${isExam?`<div class="exam-head"><span>DMV EXAM SIMULATION</span><b>09:${String(59-index*5).padStart(2,'0')}<small>TIME LEFT</small></b></div>`:''}${progress(isExam?'General Knowledge':'Quick Practice · Air Brakes')}${!isExam?`<button class="practice-auto ${autoAdvance?'enabled':''}" type="button" role="switch" aria-checked="${autoAdvance}"><span><i>ϟ</i><b>Auto Advance</b><small>Automatically move to the next question</small></span><em></em></button>`:''}<div class="question-label">QUESTION</div><h3>${q[0]}</h3><div class="session-answers">${q[1].map((a,i)=>`<button data-i="${i}" class="${isExam&&examAnswers[index]===i?'selected':''}"><b>${String.fromCharCode(65+i)}</b>${a}</button>`).join('')}</div><div class="session-feedback" hidden></div><div class="session-controls"><span>${isExam?`Answered ${examAnswers.filter(x=>x!==null).length}/10`:`Score ${score}/${index+(answered?1:0)}`}</span><button class="next-question" ${isExam&&examAnswers[index]===null?'disabled':''}>${index===9?(isExam?'Finish exam':'See result'):'Next question →'}</button></div></div>`;stage.querySelector('.practice-auto')?.addEventListener('click',()=>{autoAdvance=!autoAdvance;renderQuestion(false)});stage.querySelectorAll('.session-answers button').forEach(b=>b.onclick=()=>selectAnswer(+b.dataset.i,q,isExam));stage.querySelector('.next-question').onclick=next}
function selectAnswer(choice,q,isExam){if(isExam){examAnswers[index]=choice;render();return}if(answered)return;answered=true;const bs=stage.querySelectorAll('.session-answers button');bs[choice].classList.add(choice===q[2]?'correct':'wrong');bs[q[2]].classList.add('correct');if(choice===q[2])score++;const f=stage.querySelector('.session-feedback');f.hidden=false;f.innerHTML=`<b>${choice===q[2]?'Correct':'Review this concept'}</b><p>${q[3]}</p>`;stage.querySelector('.session-controls span').textContent=`Score ${score}/${index+1}`;if(autoAdvance)autoAdvanceTimeout=setTimeout(next,1600)}
function next(){clearTimeout(autoAdvanceTimeout);if(mode==='practice'&&!answered)return;if(index<9){index++;answered=false;flipped=false;render()}else showResult()}function showResult(){clearTimeout(autoAdvanceTimeout);const finalScore=mode==='exam'?examAnswers.reduce((n,a,i)=>n+(a===exam[i][2]),0):score;stage.innerHTML=`<div class="session-result"><span>✓</span><h3>${mode==='exam'?'Sample exam complete':'Practice complete'}</h3><strong>${finalScore}/10</strong><p>${finalScore>=8?'Strong work. You are building test-day readiness.':'Review the explanations and strengthen the missed concepts.'}</p><button id="retry">Try again</button></div>`;stage.querySelector('#retry').onclick=()=>{index=0;score=0;answered=false;examAnswers=Array(10).fill(null);render()}}
function renderCard(){const c=cards[index];stage.innerHTML=`<div class="flash-session app-flash-session"><div class="flash-progress"><div><b>Air Brakes Flashcards</b><span>Card ${index+1} of 10</span></div><i><em style="width:${(index+1)*10}%"></em></i></div><div class="app-flash-card ${flipped?'answer-side':'question-side'}">${flipped?`<span class="answer-label">CORRECT ANSWER</span><div class="answer-panel"><i>✓</i><h3>${c[2]}</h3></div><h4>How well did you know this?</h4><div class="rating-grid"><button data-rating="again">Again</button><button data-rating="hard">Hard</button><button data-rating="good">Good</button><button data-rating="easy">Easy</button></div><button class="why-button"><span>●</span><b>Why</b><em>Show more⌄</em></button>`:`<span class="question-pill">ⓘ&nbsp; QUESTION</span><i class="question-icon">?</i><h3>${c[1]}</h3><button class="reveal-answer">☝&nbsp; Tap to reveal answer</button>`}</div><div class="flash-nav"><button class="flash-prev" ${index===0?'disabled':''}>‹&nbsp; Previous</button><button class="flash-next">Next &nbsp;›</button></div><button class="restart-deck">↻&nbsp; Restart Deck</button></div>`;const reveal=stage.querySelector('.reveal-answer');if(reveal)reveal.onclick=()=>{flipped=true;renderCard()};stage.querySelectorAll('[data-rating]').forEach(button=>button.onclick=advanceCard);stage.querySelector('.flash-prev').onclick=()=>{if(index>0){index--;flipped=false;renderCard()}};stage.querySelector('.flash-next').onclick=advanceCard;stage.querySelector('.restart-deck').onclick=()=>{index=0;flipped=false;renderCard()}}function advanceCard(){if(index<9){index++;flipped=false;renderCard()}else{stage.innerHTML=`<div class="session-result"><span>✓</span><h3>Deck complete</h3><strong>10 cards</strong><p>You reviewed the full Air Brakes sample deck.</p><button id="retry">Review again</button></div>`;stage.querySelector('#retry').onclick=()=>{index=0;flipped=false;renderCard()}}}render();
